//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IO.View.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IO.View.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to abandon this QC setup?.
        /// </summary>
        public static string AbandonQcSetupConfirm {
            get {
                return ResourceManager.GetString("AbandonQcSetupConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abandon QC Setup Confirmation.
        /// </summary>
        public static string AbandonQcTestSetup {
            get {
                return ResourceManager.GetString("AbandonQcTestSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to abandon this setup?.
        /// </summary>
        public static string AbandonSetupConfirm {
            get {
                return ResourceManager.GetString("AbandonSetupConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abandon Setup Confirmation.
        /// </summary>
        public static string AbandonTestSetup {
            get {
                return ResourceManager.GetString("AbandonTestSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Aborted.
        /// </summary>
        public static string Aborted {
            get {
                return ResourceManager.GetString("Aborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software version: {0}
        ///Firmware version : {1}
        ///Total results: {2}
        ///Queued results: {3}
        ///Storage space available: {4}
        ///Serial number: {5}.
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About IO.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Assay Type.
        /// </summary>
        public static string AddNewAssay {
            get {
                return ResourceManager.GetString("AddNewAssay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        public static string Administrator {
            get {
                return ResourceManager.GetString("Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Test Results.
        /// </summary>
        public static string AllResults {
            get {
                return ResourceManager.GetString("AllResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assay Settings.
        /// </summary>
        public static string AssaySettings {
            get {
                return ResourceManager.GetString("AssaySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Assay provided is invalid..
        /// </summary>
        public static string AssayUpdateFailed {
            get {
                return ResourceManager.GetString("AssayUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assay Version.
        /// </summary>
        public static string AssayVersion {
            get {
                return ResourceManager.GetString("AssayVersion", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap Atlas {
            get {
                object obj = ResourceManager.GetObject("Atlas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not entered a Specimen ID.
        ///Would you like the Reader to assign a reference number for future identification?.
        /// </summary>
        public static string AutoSampleId {
            get {
                return ResourceManager.GetString("AutoSampleId", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap Back_icon {
            get {
                object obj = ResourceManager.GetObject("Back_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Barcode_scan {
            get {
                object obj = ResourceManager.GetObject("Barcode_scan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Blank_Background {
            get {
                object obj = ResourceManager.GetObject("Blank_Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Test.
        /// </summary>
        public static string CancelTest {
            get {
                return ResourceManager.GetString("CancelTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to cancel the current test?
        ///Test data and the specimen will be lost..
        /// </summary>
        public static string CancelTestConfirm {
            get {
                return ResourceManager.GetString("CancelTestConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Reader cannot eject at this time..
        /// </summary>
        public static string CannotEject {
            get {
                return ResourceManager.GetString("CannotEject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartridge Code.
        /// </summary>
        public static string CartridgeCode {
            get {
                return ResourceManager.GetString("CartridgeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartridge Error.
        /// </summary>
        public static string CartridgeError {
            get {
                return ResourceManager.GetString("CartridgeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cartridge barcode could not be read.
        ///Eject, check barcode and try again..
        /// </summary>
        public static string CartridgeErrorConfirm {
            get {
                return ResourceManager.GetString("CartridgeErrorConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking For Latest Tests.
        /// </summary>
        public static string CheckingForAssays {
            get {
                return ResourceManager.GetString("CheckingForAssays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To enable a new test to start,
        ///please close the reader drawer
        ///after removing a used Cartridge.
        /// </summary>
        public static string CloseReaderDrawer {
            get {
                return ResourceManager.GetString("CloseReaderDrawer", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap Confirm_sample {
            get {
                object obj = ResourceManager.GetObject("Confirm_sample", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Specimen is Correctly Loaded.
        /// </summary>
        public static string ConfirmSample {
            get {
                return ResourceManager.GetString("ConfirmSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact No..
        /// </summary>
        public static string ContactNo {
            get {
                return ResourceManager.GetString("ContactNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        public static string Daily {
            get {
                return ResourceManager.GetString("Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Policy.
        /// </summary>
        public static string DataPolicy {
            get {
                return ResourceManager.GetString("DataPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date &amp; Time.
        /// </summary>
        public static string DateAndTime {
            get {
                return ResourceManager.GetString("DateAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.O.B..
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete User Account.
        /// </summary>
        public static string DeleteUser {
            get {
                return ResourceManager.GetString("DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this user account?.
        /// </summary>
        public static string DeleteUserConfirm {
            get {
                return ResourceManager.GetString("DeleteUserConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} DETECTED.
        /// </summary>
        public static string Detected {
            get {
                return ResourceManager.GetString("Detected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        public static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do Not Quarantine.
        /// </summary>
        public static string DoNotQuarantine {
            get {
                return ResourceManager.GetString("DoNotQuarantine", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap Download {
            get {
                object obj = ResourceManager.GetObject("Download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit QCDetails.
        /// </summary>
        public static string EditQcDetails {
            get {
                return ResourceManager.GetString("EditQcDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View/Edit User Account.
        /// </summary>
        public static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If there is a used Cartridge in the drawer please remove it and close the drawer. If not please press Continue..
        /// </summary>
        public static string EmptyReaderDrawer {
            get {
                return ResourceManager.GetString("EmptyReaderDrawer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter New Password.
        /// </summary>
        public static string EnterNewPassword {
            get {
                return ResourceManager.GetString("EnterNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Patient Details.
        /// </summary>
        public static string EnterPatientDetails {
            get {
                return ResourceManager.GetString("EnterPatientDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter QC Specimen ID or Scan Barcode.
        /// </summary>
        public static string EnterQcSampleId {
            get {
                return ResourceManager.GetString("EnterQcSampleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Specimen ID or Scan Barcode.
        /// </summary>
        public static string EnterSampleId {
            get {
                return ResourceManager.GetString("EnterSampleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Specimen ID entered has already been tested. Please enter a unique specimen ID..
        /// </summary>
        public static string EnterUniqueSampleId {
            get {
                return ResourceManager.GetString("EnterUniqueSampleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter User Account Details.
        /// </summary>
        public static string EnterUser {
            get {
                return ResourceManager.GetString("EnterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cartridge is passed its expiry date.
        ///The test cannot be run..
        /// </summary>
        public static string ExpiredCartridgeConfirm {
            get {
                return ResourceManager.GetString("ExpiredCartridgeConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Data.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred exporting the data.
        /// </summary>
        public static string ExportError {
            get {
                return ResourceManager.GetString("ExportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: THIS IS AN UNCONTROLLED FILE
        ///
        ///Date and time of export: {0} UTC
        ///Instrument ID: {1}
        ///
        ///.
        /// </summary>
        public static string ExportHeader {
            get {
                return ResourceManager.GetString("ExportHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A matching file already exists. This file will be overwritten.
        ///WARNING: ANY DATA IN THE EXISTING FILE WILL BE LOST.
        /// </summary>
        public static string ExportOverwrite {
            get {
                return ResourceManager.GetString("ExportOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} file has been saved successfully.
        ///ATTENTION: THIS FILE IS UNCONTROLLED..
        /// </summary>
        public static string ExportSuccess {
            get {
                return ResourceManager.GetString("ExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This instrument has developed a fault.
        ///Please try restarting, or contact your sales
        ///representative with the fault reference below..
        /// </summary>
        public static string Fault {
            get {
                return ResourceManager.GetString("Fault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software version {0}.
        /// </summary>
        public static string FirmwareVersion {
            get {
                return ResourceManager.GetString("FirmwareVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for investigation use only.
        /// </summary>
        public static string ForInvestigationUseOnly {
            get {
                return ResourceManager.GetString("ForInvestigationUseOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap Help_icon {
            get {
                object obj = ResourceManager.GetObject("Help_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Help_icon_selected {
            get {
                object obj = ResourceManager.GetObject("Help_icon_selected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Home_icon {
            get {
                object obj = ResourceManager.GetObject("Home_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Home_icon_selected {
            get {
                object obj = ResourceManager.GetObject("Home_icon_selected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        public static string Ignore {
            get {
                return ResourceManager.GetString("Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Cartridge Detected.
        /// </summary>
        public static string IncorrectCartridge {
            get {
                return ResourceManager.GetString("IncorrectCartridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The detected cartridge cannot be run on this
        ///Reader. Would you like to add this test?.
        /// </summary>
        public static string IncorrectCartridgeConfirm {
            get {
                return ResourceManager.GetString("IncorrectCartridgeConfirm", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap Instrument_drawer_open {
            get {
                object obj = ResourceManager.GetObject("Instrument_drawer_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument Configuration.
        /// </summary>
        public static string InstrumentConfiguration {
            get {
                return ResourceManager.GetString("InstrumentConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument Drawer Open.
        /// </summary>
        public static string InstrumentDrawerOpen {
            get {
                return ResourceManager.GetString("InstrumentDrawerOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument Failed To Initialise.
        /// </summary>
        public static string InstrumentFailedToInitialise {
            get {
                return ResourceManager.GetString("InstrumentFailedToInitialise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument Name.
        /// </summary>
        public static string InstrumentName {
            get {
                return ResourceManager.GetString("InstrumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        public static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The credentials are invalid..
        /// </summary>
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User Name Or Password.
        /// </summary>
        public static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The User Name or Password entered was not recognised.
        ///Please re-enter this information or select Cancel..
        /// </summary>
        public static string InvalidLoginText {
            get {
                return ResourceManager.GetString("InvalidLoginText", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap IO {
            get {
                object obj = ResourceManager.GetObject("IO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap io_processing {
            get {
                object obj = ResourceManager.GetObject("io_processing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap io_processing_2 {
            get {
                object obj = ResourceManager.GetObject("io_processing_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap Load_cartridge {
            get {
                object obj = ResourceManager.GetObject("Load_cartridge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Load_sample {
            get {
                object obj = ResourceManager.GetObject("Load_sample", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Cartridge into Instrument.
        /// </summary>
        public static string LoadCartridge {
            get {
                return ResourceManager.GetString("LoadCartridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Specimen into Cartridge.
        /// </summary>
        public static string LoadSample {
            get {
                return ResourceManager.GetString("LoadSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        public static string Locked {
            get {
                return ResourceManager.GetString("Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap Login_icon {
            get {
                object obj = ResourceManager.GetObject("Login_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Login_icon_selected {
            get {
                object obj = ResourceManager.GetObject("Login_icon_selected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to log out?.
        /// </summary>
        public static string LogoutConfirm {
            get {
                return ResourceManager.GetString("LogoutConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu.
        /// </summary>
        public static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu (admin account).
        /// </summary>
        public static string MainMenuAdmin {
            get {
                return ResourceManager.GetString("MainMenuAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of administrators ({0}) already exist in the system.
        /// </summary>
        public static string MaximumAdministrators {
            get {
                return ResourceManager.GetString("MaximumAdministrators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Information.
        /// </summary>
        public static string MissingInformation {
            get {
                return ResourceManager.GetString("MissingInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter data to all boxes to enable tracking
        ///and future tracing of test results.
        /// </summary>
        public static string MissingInformationText {
            get {
                return ResourceManager.GetString("MissingInformationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative.
        /// </summary>
        public static string Negative {
            get {
                return ResourceManager.GetString("Negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        public static string Never {
            get {
                return ResourceManager.GetString("Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password and Verify Password must match..
        /// </summary>
        public static string NewAndVerifyMustMatch {
            get {
                return ResourceManager.GetString("NewAndVerifyMustMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No help is available for this screen.
        /// </summary>
        public static string NoHelp {
            get {
                return ResourceManager.GetString("NoHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No New Assays.
        /// </summary>
        public static string NoNewAssays {
            get {
                return ResourceManager.GetString("NoNewAssays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no new assays available.
        /// </summary>
        public static string NoNewAssaysHaveBeenFound {
            get {
                return ResourceManager.GetString("NoNewAssaysHaveBeenFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No compatible removable storage devices have been found..
        /// </summary>
        public static string NoRemovableStorage {
            get {
                return ResourceManager.GetString("NoRemovableStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} NOT DETECTED.
        /// </summary>
        public static string NotDetected {
            get {
                return ResourceManager.GetString("NotDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator ID.
        /// </summary>
        public static string OperatorId {
            get {
                return ResourceManager.GetString("OperatorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Expired.
        /// </summary>
        public static string PasswordExpired {
            get {
                return ResourceManager.GetString("PasswordExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has expired.
        ///Please renew your password on the following screen..
        /// </summary>
        public static string PasswordExpiredConfirm {
            get {
                return ResourceManager.GetString("PasswordExpiredConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Rules.
        /// </summary>
        public static string PasswordRules {
            get {
                return ResourceManager.GetString("PasswordRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient ID.
        /// </summary>
        public static string PatientId {
            get {
                return ResourceManager.GetString("PatientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanent System.
        /// </summary>
        public static string PermanentSystem {
            get {
                return ResourceManager.GetString("PermanentSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive.
        /// </summary>
        public static string Positive {
            get {
                return ResourceManager.GetString("Positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///Press Back to return.
        /// </summary>
        public static string PressBackToReturn {
            get {
                return ResourceManager.GetString("PressBackToReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No printer is available.
        /// </summary>
        public static string PrinterNotFound {
            get {
                return ResourceManager.GetString("PrinterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Options.
        /// </summary>
        public static string PrintOptions {
            get {
                return ResourceManager.GetString("PrintOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print To File.
        /// </summary>
        public static string PrintToFile {
            get {
                return ResourceManager.GetString("PrintToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QC Test Dismissal.
        /// </summary>
        public static string QcTestDismissal {
            get {
                return ResourceManager.GetString("QcTestDismissal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only an Administrator can dismiss a QC Test.
        ///Please log in to a current Administrator account..
        /// </summary>
        public static string QcTestDismissalText {
            get {
                return ResourceManager.GetString("QcTestDismissalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QC Test Due.
        /// </summary>
        public static string QcTestDue {
            get {
                return ResourceManager.GetString("QcTestDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATTENTION: QC Test is due to be run on this Reader.
        ///Would you like to run this test now?.
        /// </summary>
        public static string QcTestDueText {
            get {
                return ResourceManager.GetString("QcTestDueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QC Test Result.
        /// </summary>
        public static string QcTestResults {
            get {
                return ResourceManager.GetString("QcTestResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QC Test Setup.
        /// </summary>
        public static string QcTestSetup {
            get {
                return ResourceManager.GetString("QcTestSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarantined.
        /// </summary>
        public static string Quarantined {
            get {
                return ResourceManager.GetString("Quarantined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reader Quarantine.
        /// </summary>
        public static string ReaderQuarantine {
            get {
                return ResourceManager.GetString("ReaderQuarantine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATTENTION: This reader has been placed under
        ///quarantine as a result of a target found during a QC test.
        ///
        ///WARNING: Only unlock the reader if the source of the target
        ///has been removed using suitable cleaning methods..
        /// </summary>
        public static string ReaderQuarantineTextAdmin {
            get {
                return ResourceManager.GetString("ReaderQuarantineTextAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATTENTION: This reader has been placed under quarantine.
        ///Please log into a current Administrator account to unlock..
        /// </summary>
        public static string ReaderQuarantineTextUser {
            get {
                return ResourceManager.GetString("ReaderQuarantineTextUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record.
        /// </summary>
        public static string Record {
            get {
                return ResourceManager.GetString("Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A cartridge may be present from an aborted test.
        ///Please remove and safely dispose of any cartridge and close the drawer..
        /// </summary>
        public static string RemoveAndDispose {
            get {
                return ResourceManager.GetString("RemoveAndDispose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PCR heater needs to be replaced.
        /// </summary>
        public static string ReplacePcrStack {
            get {
                return ResourceManager.GetString("ReplacePcrStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review QC Test Input.
        /// </summary>
        public static string ReviewQcTest {
            get {
                return ResourceManager.GetString("ReviewQcTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Test Input.
        /// </summary>
        public static string ReviewTest {
            get {
                return ResourceManager.GetString("ReviewTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specimen ID.
        /// </summary>
        public static string SampleId {
            get {
                return ResourceManager.GetString("SampleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searched Test results.
        /// </summary>
        public static string SearchedResults {
            get {
                return ResourceManager.GetString("SearchedResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Test Results.
        /// </summary>
        public static string SearchTestResults {
            get {
                return ResourceManager.GetString("SearchTestResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second.
        /// </summary>
        public static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Test To Add.
        /// </summary>
        public static string SelectNewAssay {
            get {
                return ResourceManager.GetString("SelectNewAssay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Settings.
        /// </summary>
        public static string ServerSettings {
            get {
                return ResourceManager.GetString("ServerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Date.
        /// </summary>
        public static string SetDate {
            get {
                return ResourceManager.GetString("SetDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Date/Time.
        /// </summary>
        public static string SetDateTime {
            get {
                return ResourceManager.GetString("SetDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Setup.
        /// </summary>
        public static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shut Down.
        /// </summary>
        public static string Shutdown {
            get {
                return ResourceManager.GetString("Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to shut the instrument down?.
        /// </summary>
        public static string ShutdownConfirm {
            get {
                return ResourceManager.GetString("ShutdownConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Idle.
        /// </summary>
        public static string SystemIdle {
            get {
                return ResourceManager.GetString("SystemIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Complete.
        /// </summary>
        public static string TestComplete {
            get {
                return ResourceManager.GetString("TestComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Complete In {0} {1}.
        /// </summary>
        public static string TestCompleteIn {
            get {
                return ResourceManager.GetString("TestCompleteIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test in progress.
        ///User: {0}.
        /// </summary>
        public static string TestInProgress {
            get {
                return ResourceManager.GetString("TestInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} TEST INVALID.
        /// </summary>
        public static string TestInvalid {
            get {
                return ResourceManager.GetString("TestInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Results.
        /// </summary>
        public static string TestResult {
            get {
                return ResourceManager.GetString("TestResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Results.
        /// </summary>
        public static string TestResults {
            get {
                return ResourceManager.GetString("TestResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Running.
        /// </summary>
        public static string TestRunning {
            get {
                return ResourceManager.GetString("TestRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Type.
        /// </summary>
        public static string TestType {
            get {
                return ResourceManager.GetString("TestType", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap Tick {
            get {
                object obj = ResourceManager.GetObject("Tick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout Settings.
        /// </summary>
        public static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout Settings.
        /// </summary>
        public static string TimeoutSettings {
            get {
                return ResourceManager.GetString("TimeoutSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Shutdown.
        /// </summary>
        public static string UnexpectedShutdown {
            get {
                return ResourceManager.GetString("UnexpectedShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Reader has recovered from an unexpected shutdown.
        ///
        ///Please ensure the Cartridge drawer is empty and closed..
        /// </summary>
        public static string UnexpectedShutdownText {
            get {
                return ResourceManager.GetString("UnexpectedShutdownText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not entered a unique Specimen ID.
        ///Would you like the Reader to append a unique reference number for future identification?.
        /// </summary>
        public static string UniqueSmpleId {
            get {
                return ResourceManager.GetString("UniqueSmpleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlocked.
        /// </summary>
        public static string Unlocked {
            get {
                return ResourceManager.GetString("Unlocked", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap Update_in_progress {
            get {
                object obj = ResourceManager.GetObject("Update_in_progress", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update In Progress.
        /// </summary>
        public static string UpdateInProgress {
            get {
                return ResourceManager.GetString("UpdateInProgress", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap USB {
            get {
                object obj = ResourceManager.GetObject("USB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        public static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Accounts Available.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        public static string Weekly {
            get {
                return ResourceManager.GetString("Weekly", resourceCulture);
            }
        }
    }
}
