..\..\..\Software\AtlasGenetics.ClassA.IOReader.Publisher\bin\Release\Publish -Engineering -File Clamp.txt
..\..\..\Software\AtlasGenetics.ClassA.IOReader.Publisher\bin\Release\Publish -Engineering -File Error.txt
..\..\..\Software\AtlasGenetics.ClassA.IOReader.Publisher\bin\Release\Publish -Engineering -File Load.txt
..\..\..\Software\AtlasGenetics.ClassA.IOReader.Publisher\bin\Release\Publish -Engineering -File Preload.txt
..\..\..\Software\AtlasGenetics.ClassA.IOReader.Publisher\bin\Release\Publish -Engineering -File Reset.txt
..\..\..\Software\AtlasGenetics.ClassA.IOReader.Publisher\bin\Release\Publish -Engineering -File StartUp.txt
..\..\..\Software\AtlasGenetics.ClassA.IOReader.Publisher\bin\Release\Publish -Engineering -File StartUpUnload.txt
..\..\..\Software\AtlasGenetics.ClassA.IOReader.Publisher\bin\Release\Publish -Engineering -File Unclamp.txt
..\..\..\Software\AtlasGenetics.ClassA.IOReader.Publisher\bin\Release\Publish -Engineering -File Unload.txt
